### PR TITLE
Tmp

### PR DESCRIPTION
**Pull request by ravijohnmark**
This Pull Request resolves Issue #11 #1 #3 

Description:
In this Pull Request we have done the following additions/edits for the code:

### CODE REVIEW

**Comment by salman-bhai** [comment]
Please fix merge conflicts!

**Comment by utkarsh23** [comment]
Any update, @ravijohnmark ?

**Comment by salman-bhai** [comment]
Are there any updates here or should we close the PR and label it as `spam`?

**Comment by salman-bhai** [comment]
spam!

**Pull request closed without merging**
