### PR TITLE
Create bubblesort.py

### PR DESCRIPTION
**Pull request by aishuj007**
This Pull Request resolves Issue #<IssueNumber>

Description:
In this Pull Request we have done the following additions/edits for the code:

Note: Delete all the text including this!
* Make sure you replace `#<IssueNumber>` with the particular Issue that you are referencing with!
* Make sure you describe the Issue properly and ask as many people as possible to review your Pull Request so that it can be merged as soon as possible!

### CODE REVIEW

**Review by mishal23 — APPROVED** [review]
Thanks for contributing! @aishuj007

**Review by mishal23 — CHANGES_REQUESTED** [review]
Please change the file name with your username (for eg. ```mishal23.py```),
and reference the issue in the comments

**Comment by salman-bhai** [comment]
Are there any updates or should we close the PR?

**Comment by sbshah97** [comment]
PR closed due to inactivity

**Pull request closed without merging**
