### PR TITLE
Have added bucket sort in python

### PR DESCRIPTION
**Pull request by praabi**
Hiii! I have not resolved any issue. I have added bucket sort into it.
Referenced #457

### CODE REVIEW

**Comment by praabi** [comment]
I have followed #11
<https://github.com/WebClub-NITK/Hacktoberfest-2k17/issues/11> for python

**Comment by salman-bhai** [comment]
@praabi that Issue is for writing a Hello World file! Please either send a Hello World Code or create a new Issue for the same!

**Comment by praabi** [comment]
shall I have to create an issue for adding bucket sort in the repo!!!

**Comment by MJ10** [comment]
@praabi yes, create a new issue for adding bucket sort

**Comment by praabi** [comment]
I have submitted the new issue along with the description .
Kindly check it and inform me if anything else require!!

**Comment by praabi** [comment]
Thank you.

**Comment by MJ10** [comment]
@praabi Great work. Just change the name of your file to your github username and the folder name to `Bucket_Sort`

**Comment by praabi** [comment]
means the folder name should be Bucket_sort and the file name will be
praabi.py!!!!

**Comment by MJ10** [comment]
Yes @praabi

**Comment by MJ10** [comment]
@praabi no need for the i/o files. Please delete them.

**Comment by MJ10** [comment]
Great Work @praabi ! Thanks for contributing!

**Comment by praabi** [comment]
Thank you for the help.

Regards
Abinash Panda
CSE grad,
CET,BBSR

**Pull request merged**
