### PR TITLE
Joslind

### PR DESCRIPTION
**Pull request by joslindcunha**
This Pull Request resolves Issue #4 

Description:
In this Pull Request we have done the following additions/edits for the code:

### CODE REVIEW

**Comment by joslindcunha** [comment]
Is it okay now ?

**Comment by salman-bhai** [comment]
There are merge conflicts yet.

**Comment by joslindcunha** [comment]
I'll try to redo all pull requests

**Comment by salman-bhai** [comment]
Sure no issues.

**Comment by salman-bhai** [comment]
SHould this PR be closed?

**Pull request closed without merging**
