### PR TITLE
ganeshpatel/binarysearch.cpp

### PR DESCRIPTION
**Pull request by ganeshpatel**
It uses pointer array so we need no define array size to some larger fix size. this is a memory efficient version of the previous code.

This Pull Request resolves Issue #<IssueNumber>

Description:
In this Pull Request we have done the following additions/edits for the code:

Note: Delete all the text including this!
* Make sure you replace `#<IssueNumber>` with the particular Issue that you are referencing with!
* Make sure you describe the Issue properly and ask as many people as possible to review your Pull Request so that it can be merged as soon as possible!

### CODE REVIEW

**Comment by ganeshpatel** [comment]
I've not found my issue listed for this problem but I have modified that program in terms of a memory efficient version.The previous one was using a predefined size array but i have created array using malloc.

**Comment by rahulsnkr** [comment]
Check the issues tab for the issue you are resolving. You can find the issue number by opening the issue. Also, put your code inside a folder named "BinarySearch"

**Comment by salman-bhai** [comment]
@ganeshpatel please feel free to edit the Issue Description in case it is not what you were looking for!

**Comment by salman-bhai** [comment]
Please do not send one line PRs else they will be marked as spam!

**Comment by salman-bhai** [comment]
spam

**Pull request closed without merging**
