### PR TITLE
Patch 9

### PR DESCRIPTION
**Pull request by mvibhamenon**
This Pull Request resolves Issue #4 

Description:
In this Pull Request we have done the following additions/edits for the code:

Note: Delete all the text including this!
* Make sure you replace `#<IssueNumber>` with the particular Issue that you are referencing with!
* Make sure you describe the Issue properly and ask as many people as possible to review your Pull Request so that it can be merged as soon as possible!

### CODE REVIEW

**Comment by mvibhamenon** [comment]
done

**Comment by salman-bhai** [comment]
@anumehaagrawal please review!

**Review by anumehaagrawal — CHANGES_REQUESTED** [review]
Please add participant details in the .txt file

**Comment by salman-bhai** [comment]
Are there any updates or should we close the PR?

**Comment by sbshah97** [comment]
PR closed due to inactivity

**Pull request closed without merging**
