### PR TITLE
program to add two numbers in python

### PR DESCRIPTION
**Pull request by ApoorvAgarwal21**
program to add two numbers using python

This Pull Request resolves Issue #<IssueNumber>

Description:
In this Pull Request we have done the following additions/edits for the code:

Note: Delete all the text including this!
* Make sure you replace `#<IssueNumber>` with the particular Issue that you are referencing with!
* Make sure you describe the Issue properly and ask as many people as possible to review your Pull Request so that it can be merged as soon as possible!

### CODE REVIEW

**Comment by ApoorvAgarwal21** [comment]
sir please help me where and how to attach .py extension file

**Comment by salman-bhai** [comment]
You just have to rename the file with a right click of your mouse :dagger:

**Comment by mishal23** [comment]
Also remove the ```code :- ``` text in your file

**Comment by salman-bhai** [comment]
@mishal23 please review!

**Comment by mishal23** [comment]
Please reference the issue in the comments, and move to a proper directory.
Also name the file as mentioned in issues.
Refer #423 issue description

**Comment by salman-bhai** [comment]
PR closed due to inactivity!

**Pull request closed without merging**
