### PR TITLE
Update ravijohnmark.html

### PR DESCRIPTION
**Pull request by galbin17**
This Pull Request resolves Issue #<IssueNumber>

Description:
In this Pull Request we have done the following additions/edits for the code:

Note: Delete all the text including this!
* Make sure you replace `#<IssueNumber>` with the particular Issue that you are referencing with!
* Make sure you describe the Issue properly and ask as many people as possible to review your Pull Request so that it can be merged as soon as possible!

### CODE REVIEW

**Review by utkarsh23 — CHANGES_REQUESTED** [review]
Please reference the issue you've resolved. If you've not resolved any issue, please mention the changes you've made in the description.

**Comment by galbin17** [comment]
i am sorry if i cant give solve for your code

i am new in coding world

Pada tanggal 28 Okt 2017 13.31, "Utkarsh Patil" <notifications@github.com>
menulis:

**Comment by salman-bhai** [comment]
Hey @galbin17 it's not that tough what Utkarsh is saying. Try looking at one of the merged PRs as to how it's done. Also look at #1 in the images how we've done! In case you're still facing an Issue, we'll guide you through. Just try to google it and work on it, I 'm pretty sure you'll be able to get it

**Comment by salman-bhai** [comment]
Any updates or should we close the PR?

**Comment by sbshah97** [comment]
PR closed due to inactivity

**Pull request closed without merging**
