### PR TITLE
Patch 1

### LINKED ISSUE #11: Add Hello World in Python
* To get started with Python, checkout the [Python Tutorial](https://docs.python.org/3/tutorial/index.html)
* Create a folder named `Python`. In that folder add a file called `<github-handle>.py`
For example mine would be `MJ10.py`

Look up the CONTRIBUTING.md Document to see how to push your code to GitHub.

### PR DESCRIPTION
**Pull request by mvibhamenon**
This Pull Request resolves #11 

Description:
In this Pull Request we have done the following additions/edits for the code:

Note: Delete all the text including this!
* Make sure you replace `#<IssueNumber>` with the particular Issue that you are referencing with!
* Make sure you describe the Issue properly and ask as many people as possible to review your Pull Request so that it can be merged as soon as possible!

### CODE REVIEW

**Comment by mvibhamenon** [comment]
Done.

**Comment by mvibhamenon** [comment]
Done

**Comment by salman-bhai** [comment]
Are there any updates or should we close the PR?

**Comment by salman-bhai** [comment]
PR closed due to inactivity!

**Pull request closed without merging**
