### PR TITLE
Create helloworldc

### PR DESCRIPTION
**Pull request by imnisarg**
This Pull Request resolves Issue #<IssueNumber>

Description:
In this Pull Request we have done the following additions/edits for the code:

Note: Delete all the text including this!
* Make sure you replace `#<IssueNumber>` with the particular Issue that you are referencing with!
* Make sure you describe the Issue properly and ask as many people as possible to review your Pull Request so that it can be merged as soon as possible!

### CODE REVIEW

**Comment by imnisarg** [comment]
adding helloworld programm

**Comment by imnisarg** [comment]
https://github.com/WebClub-NITK/Hacktoberfest-2k17/pull/211/commits/01e8323a84f966a090bcc389f9d531352fdb953c

**Comment by salman-bhai** [comment]
wrong directory

**Comment by utkarsh23** [comment]
Any update, @imnisarg ?

**Comment by salman-bhai** [comment]
Are there any updates here or should we close the PR and label it as `spam`?

**Comment by salman-bhai** [comment]
spam!

**Pull request closed without merging**
