### PR TITLE
Added palindrome solution and folder structure

### PR DESCRIPTION
**Pull request by captainswain**
This Pull Request resolves Issue #574

Description:
Added my palindrome solution and created the folder structure for others.

### CODE REVIEW

**Comment by salman-bhai** [comment]
ANy updates here?

**Comment by pvgupta24** [comment]
@captainswain please make the suggested changes soon. Rest looks good. :+1:

**Comment by salman-bhai** [comment]
Close solution in 24 hours if there are no updates!

**Comment by salman-bhai** [comment]
PR closed due to inactivity!

**Pull request closed without merging**
